### ISSUE TITLE
Separate consumer/producer per command

### ISSUE THREAD

**Issue by lakiboy** [SimpleBus/RabbitMQBundleBridge#14]
It is a good practice to maintain a separate queue for a single job e.g. `send_invites`, `process_image` etc. At the moment default setup uses a single queue for all commands i.e. `asynchronous_commands`. I might want to have 2-3 workers for image processing, 1 worker for email invites etc. 

This is really easy to setup with `supervisor` e.g.

    [program:upload_image]
    directory    = /var/www/symfony
    user         = symfony
    command      = ./app/console rabbitmq:consumer upload_image
    numprocs     = 2
    process_name = %(program_name)s_%(process_num)01d

To overcome default behaviour I implemented `DelegatingProducer`

```php
<?php

namespace MyProject\CoreBundle\SimpleBus;

use OldSound\RabbitMqBundle\RabbitMq\Fallback;
use OldSound\RabbitMqBundle\RabbitMq\ProducerInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

class DelegatingProducer extends Fallback
{
    private $container;

    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }

    public function publish($msg, $routingKey = '', $props = array())
    {
        if (!isset($props['producer'])) {
            throw new \RuntimeException(sprintf('No "producer" key defined in %s', __METHOD__));
        }

        /** @var ProducerInterface $producer */
        $producer = $this->container->get(sprintf('old_sound_rabbit_mq.%s_producer', $props['producer']));

        unset($props['producer']);

        return $producer->publish($msg, $routingKey, $props);
    }
}
```

Example config:

```yaml
old_sound_rabbit_mq:
    producers:
        upload_image:
            connection:        default
            exchange_options:  { name: upload_image, type: direct }
            auto_setup_fabric: false
    consumers:
        ...
        upload_image:
            connection:        default
            exchange_options:  { name: upload_image, type: direct }
            queue_options:     { name: upload_image }
            callback:          simple_bus.rabbit_mq_bundle_bridge.commands_consumer
            auto_setup_fabric: false
            qos_options:       { prefetch_count: 10 }

simple_bus_rabbit_mq_bundle_bridge:
    commands:
        producer_service_id: my_project.simple_bus.delegating_producer
```

Basically each message must know the producer it should be invoked in. To discover producer name `AdditionalPropertiesResolver` could be implemented. 

For example:

```php
<?php

namespace MyProject\CoreBundle\SimpleBus;

use SimpleBus\Asynchronous\Properties\AdditionalPropertiesResolver;

class ProducerNameResolver implements AdditionalPropertiesResolver
{
    public function resolveAdditionalPropertiesFor($message)
    {
        $name = self::tableize(substr(get_class($message), strrpos(get_class($message), '\\') + 1));

        if (substr($name, -8) === '_command') {
            $name = substr($name, 0, strlen($name) - 8);
        } elseif (substr($name, -6) === '_event') {
            $name = substr($name, 0, strlen($name) - 6);
        }

        return ['producer' => $name];
    }

    /**
     * Taken from Doctrine\Common\Inflector.
     *
     * @param string $word
     *
     * @return string
     */
    private static function tableize($word)
    {
        return strtolower(preg_replace('~(?<=\\w)([A-Z])~', '_$1', $word));
    }
}
```

e.g. `UploadImageCommand` resolves to `upload_image`, thus invoking `old_sound_rabbit_mq.upload_image_producer` within `DelegatingProducer`.

Same approach is applicable for events. In fact same producer instance could be used. 

My question to you. Are you interested in a pull request with above 2 classes + tests?
